### ISSUE TITLE
Security audit

### ISSUE THREAD

**Issue by njam** [cargomedia/pulsar-rest-api#52]
- Check that an attacker cannot run tasks without authentication.
- Check that authenticated users cannot run other commands than `pulsar`.
- Disallow pulsar tasks: invoke, shell (configurable?)

**Comment by vogdb** [comment]
> - Check that an attacker cannot run tasks without authentication.

- Verified. For that pulsar-rest-api must be launched with filled `auth` in its config.

> - Check that authenticated users cannot run other commands than `pulsar`.

- Verified. Restricted by design. All the pulsar tasks are executed by `require('child_process').spawn('pulsar', this.getCommandArgs())`. So it is impossible to run anything except `pulsar`.

> - Disallow pulsar tasks: invoke, shell (configurable?)

Not implemented =(. Can you enlighten me here?

**Comment by njam** [comment]
> invoke, shell

These two tasks can be used to execute arbitrary commands (e.g. `pulsar foo bar invoke -s command="any command here`).
The idea is to disallow these two commands therefore by default.

**Comment by vogdb** [comment]
Ok. You've just mentioned the word configurable. So I thought I must implement some list of illegal commands that should be configurable. Now I will just hardcode this list of two commands in Job class or somewhere near it.

**Comment by njam** [comment]
sgtm!
